package com.sayac;

public class Runner {

	public static void main(String[] args) {
		String metin = "Vor einigen Wochen hatten wir knapp 24 Stunden lang kein Internet und kein Telefon. An diesem Tag haben wir als Familie gemerkt, wie abhängig wir mittlerweile von dieser Technologie sind. Du auch? Es fing mit der Unterhaltung an. Ich höre gerne und viele Podcasts – am Freitag immer einen Kinopodcast der BBC. Diesen konnte ich nicht herunterladen. Naja, das war natürlich nicht schlimm, aber ich dachte mir: Ok, dann höre ich eben Musik. Ich höre Musik mittlerweile immer über Spotify – auch das ist ein Internetdienst und war demzufolge nicht verfügbar. Kein Podcast, keine Musik. Auch kein Hörbuch von Audible, denn ich hatte keines heruntergeladen. Nichts zu hören! Selbst das Radio streamen wir heute über das Internet. CD-Player oder Schallplattenspieler haben wir nicht mehr. Nur ein DAB-Radio im Bad konnte uns helfen, kurz die Nachrichten zu hören. Mein Sohn konnte nicht Minecraft spielen, sein Tablet war nutzlos. Eine neue Episode Slow German machen oder ein neues Video für YouTube – auch nicht möglich.\r\n"
				+ "\r\n"
				+ "Am Abend wollten wir einen Film sehen, aber auch da wurde uns klar: Unsere Fernsehgewohnheiten haben sich geändert. Während wir früher einfach das sahen, was gerade im Live-Fernsehen kam, schauen wir heute nur noch über Netflix oder Amazon Prime und all diese Dienste fern. Wir schauen gezielt Filme oder Serien im Stream. Auch das war ohne Internet nicht möglich. Die Mediatheken der großen Sender waren ebenfalls lahmgelegt. Also blieb nur das Live-Fernsehen, und das war an diesem Abend langweilig. Für mich alles kein Problem, denn ich bin eine Leseratte. Mein Buch funktionierte auch ohne Strom und Internet. Das von meinem Sohn auch. Aber mein Mann surft gerne abends im Internet, er liest viel auf dem iPad – ihm war also langweilig.\r\n"
				+ "\r\n"
				+ "Der nächste Tag brachte dann noch mehr Probleme mit sich.Ich fange morgens immer an, erstmal eine halbe Stunde Yoga zu machen. Ich nutze dafür eine App, die mir die Asanas zusammenstellt. Ohne Internet konnte diese App nichts laden. Auch meine Meditations-App funktionierte natürlich nicht. Meine Arbeit ist komplett unmöglich ohne das Internet. Zum einen habe ich Konferenzen mit meinen Kolleg:innen, meistens über Microsoft Teams oder Zoom. Das war ohne Internet nicht möglich. Außerdem ist mein Job ja, dass ich als Community Managerin oder Social Media Managerin arbeite – aber Facebook, Instagram, Twitter und YouTube sind Dienste im Internet. Ich musste an diesem Tag also aufgeben und konnte nicht arbeiten, denn auch Mails erreichten mich nicht. Alleine anzurufen und meinem Chef zu sagen, dass ich kein Internet habe, war schwierig – denn normalweise rufe ich ihn über Teams an oder ich schaue in Teams nach seiner Telefonnummer. Jetzt musste ich sie anders herausfinden.\r\n"
				+ "\r\n"
				+ "Auch die Videokonferenz mit meinen Eltern konnte nicht stattfinden, der Kontakt zu Freunden und Familie in Zeiten der Pandemie war abgebrochen. Unsere Bestellung bei einem Lieferdienst für Bio-Lebensmittel war nicht möglich, denn auch die geht immer über das Internet. Ich konnte keine neuen Bücher für meinen Sohn bestellen, denn auch das mache ich bei einem sozialen Buchversand über das Internet. Keine neuen Klamotten kaufen, kein Lego, kein Geschenk für den nächsten Kindergeburtstag. Das Internet hat sich mittlerweile in so viele unserer Lebensbereiche eingeschlichen! Wir sind abhängig von Online-Banking und Online-Shopping, Online-Arbeit und Online-Homeschooling.\r\n"
				+ "\r\n"
				+ "Gut, ich gebe zu, ich habe hier etwas übertrieben. Denn natürlich habe ich sofort einen Hotspot über mein Handy eingerichtet und die wichtigsten Dinge dann über meinen mobilen Datentarif gemacht. Aber dennoch haben diese 24 Stunden uns die Augen geöffnet. Unser Leben hat sich in den vergangenen Jahren sehr geändert. Es ist normal geworden, eine gute Datenverbindung zu haben und Filme ohne Ruckeln im Stream anzusehen. Dabei ist Deutschland übrigens gar nicht so gut im Vergleich mit anderen Ländern! Was die Datenrate angeht ist Deutschland derzeit auf dem 31. Platz weltweit. Und jetzt sag mal ganz ehrlich: Bist Du auch so abhängig vom Internet wie wir? Und dann ist da noch der nächste, viel schlimmere Gedanke: Was wäre, wenn wir keinen Strom hätten? ";

		Utilities obj = new Utilities();

		obj.kelimeSay(metin);

	}
}
